name: Release

on:
  push:
    tags: ["v*"]

jobs:
  Release:
    permissions:
      id-token: write
      packages: write
      contents: write

    strategy:
      matrix:
        GOOS: [linux]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@v2

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - uses: docker/setup-buildx-action@v3

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.21.7'
          check-latest: true

      - name: Generate distribution sources
        run: make generate-sources

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: goreleaser/goreleaser-action@v5
        if: steps.cache.outputs.cache-hit != 'true' # do not run if cache hit
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 2h
        env:
          GOOS: ${{ matrix.GOOS }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          COSIGN_EXPERIMENTAL: true

      - uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: dist/*/*
